# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq_ZnYCnoGhiQ1KisUW1Gml2irBLzeyi
"""

import pandas as pd
import io
from google.colab import files


uploaded = files.upload()


fname = next(iter(uploaded))
df = pd.read_csv(io.BytesIO(uploaded[fname]))


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df